version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: un_documents_db
    environment:
      POSTGRES_DB: un_documents
      POSTGRES_USER: un_user
      POSTGRES_PASSWORD: un_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
